// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9AilOkb0wHgHG-I2X4h9JXU-bVaFyXss',
    appId: '1:357720496412:web:76b0f6379e581bc6c3c2d9',
    messagingSenderId: '357720496412',
    projectId: 'mekatronik-qr-management',
    authDomain: 'mekatronik-qr-management.firebaseapp.com',
    storageBucket: 'mekatronik-qr-management.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQTsH9iigIjS8vPIZ5DyDypQT5dug1dXA',
    appId: '1:357720496412:android:e7c90424460887bbc3c2d9',
    messagingSenderId: '357720496412',
    projectId: 'mekatronik-qr-management',
    storageBucket: 'mekatronik-qr-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQYcz2tOVbILP9ODrkzdjxnL32WUHTK9U',
    appId: '1:357720496412:ios:eb7699edb5a03107c3c2d9',
    messagingSenderId: '357720496412',
    projectId: 'mekatronik-qr-management',
    storageBucket: 'mekatronik-qr-management.appspot.com',
    iosBundleId: 'com.example.qrEmployee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQYcz2tOVbILP9ODrkzdjxnL32WUHTK9U',
    appId: '1:357720496412:ios:e29344d2dda93462c3c2d9',
    messagingSenderId: '357720496412',
    projectId: 'mekatronik-qr-management',
    storageBucket: 'mekatronik-qr-management.appspot.com',
    iosBundleId: 'com.example.qrEmployee.RunnerTests',
  );
}
